In [33]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

%matplotlib inline

In [34]:
data = pd.read_csv('Sales_Transactions_Dataset_Weekly.csv')

In [35]:
data.head()

Product_Code  W0  W1  W2  W3  W4  W5  W6  W7  W8  ...  Normalized 42  \
0           P1  11  12  10   8  13  12  14  21   6  ...           0.06   
1           P2   7   6   3   2   7   1   6   3   3  ...           0.20   
2           P3   7  11   8   9  10   8   7  13  12  ...           0.27   
3           P4  12   8  13   5   9   6   9  13  13  ...           0.41   
4           P5   8   5  13  11   6   7   9  14   9  ...           0.27   

   Normalized 43  Normalized 44  Normalized 45  Normalized 46  Normalized 47  \
0           0.22           0.28           0.39           0.50           0.00   
1           0.40           0.50           0.10           0.10           0.40   
2           1.00           0.18           0.18           0.36           0.45   
3           0.47           0.06           0.12           0.24           0.35   
4           0.53           0.27           0.60           0.20           0.20   

   Normalized 48  Normalized 49  Normalized 50  Normalized 51  
0           0.22           0.17           0.11           0.39  
1           0.50           0.10           0.60           0.00  
2           1.00           0.45           0.45           0.36  
3           0.71           0.35           0.29           0.35  
4           0.13           0.53           0.33           0.40  

[5 rows x 107 columns]

In [36]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 811 entries, 0 to 810
Columns: 107 entries, Product_Code to Normalized 51
dtypes: float64(52), int64(54), object(1)
memory usage: 678.0+ KB


In [37]:
data = data.drop('Product_Code', axis=1)
data.head()

W0  W1  W2  W3  W4  W5  W6  W7  W8  W9  ...  Normalized 42  Normalized 43  \
0  11  12  10   8  13  12  14  21   6  14  ...           0.06           0.22   
1   7   6   3   2   7   1   6   3   3   3  ...           0.20           0.40   
2   7  11   8   9  10   8   7  13  12   6  ...           0.27           1.00   
3  12   8  13   5   9   6   9  13  13  11  ...           0.41           0.47   
4   8   5  13  11   6   7   9  14   9   9  ...           0.27           0.53   

   Normalized 44  Normalized 45  Normalized 46  Normalized 47  Normalized 48  \
0           0.28           0.39           0.50           0.00           0.22   
1           0.50           0.10           0.10           0.40           0.50   
2           0.18           0.18           0.36           0.45           1.00   
3           0.06           0.12           0.24           0.35           0.71   
4           0.27           0.60           0.20           0.20           0.13   

   Normalized 49  Normalized 50  Normalized 51  
0           0.17           0.11           0.39  
1           0.10           0.60           0.00  
2           0.45           0.45           0.36  
3           0.35           0.29           0.35  
4           0.53           0.33           0.40  

[5 rows x 106 columns]

In [38]:
X = data.iloc[:,0:52]
X_normalized = data.iloc[:,53:106]

In [39]:
from sklearn.cluster import KMeans

In [40]:
kmeans = KMeans(n_clusters=2, random_state=0).fit(X)

In [41]:
kmeans_norm = KMeans(n_clusters=2, random_state=0).fit(X_normalized)

In [42]:
kmeans.labels_

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [43]:
kmeans_norm.labels_

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [47]:
kmeans.cluster_centers_

array([[ 4.3250366 ,  4.30893119,  4.37481698,  4.44948755,  4.57540264,
         4.60468521,  4.56076135,  4.59297218,  4.55783309,  4.5988287 ,
         4.54026354,  4.73938507,  4.66617862,  4.58272328,  4.73352855,
         4.75256223,  4.7057101 ,  4.85358712,  4.82430454,  4.65300146,
         4.71742313,  4.8374817 ,  5.02342606,  5.18301611,  5.89604685,
         5.7057101 ,  3.39238653,  3.48023426,  3.45827233,  3.43777452,
         3.55783309,  3.65885798,  3.64421669,  3.76281113,  3.86090776,
         3.90190337,  3.81405564,  3.91215227,  3.93850659,  3.8477306 ,
         3.92093704,  3.97803807,  4.02928258,  4.01317716,  4.13616398,
         4.15080527,  4.25622255,  4.30893119,  4.44802343,  4.83016105,
         5.21376281,  5.99560761],
       [33.328125  , 34.8515625 , 36.1484375 , 37.828125  , 36.25      ,
        35.40625   , 37.25      , 36.2265625 , 37.671875  , 36.8046875 ,
        37.8046875 , 36.03125   , 37.3671875 , 36.921875  , 37.515625  ,
        38.28906

In [48]:
kmeans_norm.cluster_centers_

array([[ 8.55417957,  0.24625387,  0.25216718,  0.25091331,  0.25705882,
         0.27413313,  0.26848297,  0.27608359,  0.27736842,  0.26380805,
         0.27250774,  0.27097523,  0.27732198,  0.28273994,  0.2769195 ,
         0.3045356 ,  0.28405573,  0.26944272,  0.28888545,  0.30151703,
         0.27547988,  0.28188854,  0.30653251,  0.31846749,  0.33010836,
         0.39130031,  0.40428793,  0.19995356,  0.21150155,  0.21343653,
         0.20495356,  0.21631579,  0.23441176,  0.22609907,  0.23475232,
         0.23883901,  0.24899381,  0.24667183,  0.24998452,  0.24952012,
         0.24198142,  0.26320433,  0.25363777,  0.27145511,  0.26182663,
         0.28126935,  0.29184211,  0.31236842,  0.29009288,  0.32069659,
         0.34845201,  0.37153251,  0.46091331],
       [46.66666667,  0.45830303,  0.48284848,  0.52527273,  0.56569697,
         0.53351515,  0.51884848,  0.55509091,  0.51921212,  0.56133333,
         0.53957576,  0.56666667,  0.54339394,  0.55866667,  0.54563636,
   